### ISSUE TITLE
Enable travis support

### ISSUE THREAD

**Issue by ignasi35** [lagom/lagom-recipes#32]
As lagom moves forward some recipes need upgrades as versions bump. It'd be great to have some form of build server to ease maintenance.

**Comment by ignasi35** [comment]
Start with something like: (?)

```yaml
language: scala
dist: trusty
sudo: required
group: edge
jdk:
  - oraclejdk8
env:
  matrix:
    - SCRIPT="cd consumer-service/consumer-service-java-sbt; sbt test"
script: bin/$SCRIPT
before_install:
    # See https://github.com/travis-ci/travis-ci/issues/4629#issuecomment-239493916
    - rm ~/.m2/settings.xml
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala*
    - $HOME/.m2/repository
before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/com.lightbend.lagom/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.lightbend.lagom/*
  - rm -r $HOME/.m2/repository/com/lightbend/lagom/*
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
notifications:
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/773aba95141768c32dae
    on_success: always
    on_failure: always

```
